enduser/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^user$', views.user_dashboard, name="user-dashboard"),
    url(r'^add/resume$', views.resume_form, name="add-resume"),
    url(r'^edit/resume/(?P<slug>[-\w]+)$', views.edit_resume_form, name="edit-resume"),
    url(r'^education$', views.education, name="education"),
    url(r'^add/education$', views.add_education, name="add-education"),
    url(r'^edit/education/(?P<id>[0-9]+)$', views.edit_education, name="edit-education"),
    url(r'^experience$', views.experience, name="experience"),
    url(r'^add/experience$', views.add_experience, name="add-experience"),
    url(r'^edit/experience/(?P<id>[0-9]+)$', views.edit_experience, name="edit-experience"),
    url(r'^skill$', views.skill, name="skill"),
    url(r'^add/skill$', views.add_skill, name="add-skill"),
    url(r'^edit/skill/(?P<id>[0-9]+)$', views.edit_skill, name="edit-skill"),
    url(r'^reference$', views.reference, name="reference"),
    url(r'^add/reference$', views.add_reference, name="add-reference"),
    url(r'^edit/reference/(?P<id>[0-9]+)$', views.edit_reference, name="edit-reference"),
    url(r'^add/setting$', views.usersetting, name="usersetting"),
    url(r'^edit/setting/(?P<id>[0-9]+)$', views.edit_usersetting, name="edit-usersetting"),
]

job/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^jobs$', views.list_job, name="list-job"),
    url(r'^job/(?P<slug>[-\w]+)$', views.detail_job, name="job-detail"),
    url(r'^post/job$', views.post_job, name="post-job"),
    url(r'^edit/job/(?P<slug>[-\w]+)$', views.edit_job, name="edit-job"),
    url(r'^apply/job/(?P<slug>[-\w]+)$', views.apply_job, name="apply-job"),
]

resume/urls.py
from django.conf.urls import url, include

from . import views

#urlpatterns = [
#    url(r'^jobs$', views.list_job, name="list-job"),
#    url(r'^job/(?P<slug>[-\w]+)$', views.detail_job, name="job-detail"),
#    url(r'^post/job$', views.post_job, name="post-job"),
#    url(r'^edit/job/(?P<slug>[-\w]+)$', views.edit_job, name="edit-job"),
#]

startup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('products.urls', namespace='products')),
    url(r'^', include('job.urls', namespace='jobs')),
    url(r'^', include('enduser.urls', namespace='enduser')),
    #url(r'^', include('resume.urls', namespace='resume')),
    url(r'^', include('investors.urls', namespace='investors')),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

resume/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

from products.utils import unique_slug_generator

class Resume(models.Model):
    applicant = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=False, null=False, help_text="Full Name")
    slug = models.SlugField(max_length=50, unique=True)
    designation = models.CharField(max_length=200, blank=True, null=True)
    career_goal=models.CharField(max_length=500, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=100, blank=True, null=True)
    email=models.EmailField(blank=False, null=False)
    website=models.URLField(blank=True, null=True)
    linkedin_url=models.URLField(blank=True, null=True)
    twitter_url=models.URLField(blank=True, null=True)
    facebook_url=models.URLField(blank=True, null=True)
    summary=models.CharField(max_length=400, blank=True, null=True)

    class Meta:
        verbose_name = 'Resume'
        verbose_name_plural = 'Resume'

    def __str__(self):
        return self.name

class Education(models.Model):
    resume = models.ForeignKey(Resume, related_name='educations')
    name = models.CharField(max_length=100, blank=False, null=False, help_text="Name of an institution")
    course = models.CharField(max_length=200, blank=False, null=False, help_text="Name of a course")
    description = models.CharField(max_length=400, blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()

    class Meta:
        verbose_name = 'Education'
        verbose_name_plural = 'Education'

    def __str__(self):
        return '{0} -> {1}'.format(self.resume.name, self.name)

    def edit_education_url(self):
        return reverse('enduser:edit-education', kwargs={'id': self.id})


class Experience(models.Model):
    resume = models.ForeignKey(Resume, related_name='experiences')
    designation = models.CharField(max_length=100, blank=True, null=True)
    company = models.CharField(max_length=100, blank=True, null=True)
    description=models.CharField(max_length=400, blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()

    class Meta:
        verbose_name='Experience'
        verbose_name_plural='Experiences'

    def __str__(self):
        return self.designation

    def edit_experience_url(self):
        return reverse('enduser:edit-experience', kwargs={'id': self.id})

class Skill(models.Model):
    resume=models.ForeignKey(Resume, related_name="skills")
    name = models.CharField(max_length=100, blank=True, null=True, help_text="Name of the skill")

    class Meta:
        verbose_name='Skill'
        verbose_name_plural='Skills'

    def __str__(self):
        return self.name

    def edit_skill_url(self):
        return reverse('enduser:edit-skill', kwargs={'id': self.id})


class Reference(models.Model):
    resume = models.ForeignKey(Resume, related_name='references')
    name_of_refree=models.CharField(max_length=100, blank=False, null=False)
    designation_of_refree = models.CharField(max_length=100, blank=False, null=False)
    phone_number=models.CharField(max_length=50, blank=False, null=False)

    class Meta:
        verbose_name='Reference'
        verbose_name_plural='References'

    def __str__(self):
        return self.name_of_refree

    def edit_reference_url(self):
        return reverse('enduser:edit-reference', kwargs={'id': self.id})

resume/views.py
from django.shortcuts import render

# Create your views here.

templates/userDashboard/user/add_education.html
{% extends 'userDashboard/index.html'%}

{% block title %}
  <title>StartupNep | Add Education</title>
{% endblock title %}

{% block pagecontent %}
  {% include 'includes/form.html' %}
{% endblock pagecontent %}

templates/userDashboard/user/add_experience.html
{% extends 'userDashboard/index.html'%}

{% block title %}
  <title>StartupNep | Add Experiences</title>
{% endblock title %}

{% block pagecontent %}
  {% include 'includes/form.html' %}
{% endblock pagecontent %}

templates/userDashboard/user/add_reference.html
{% extends 'userDashboard/index.html'%}

{% block title %}
  <title>StartupNep | Add References</title>
{% endblock title %}

{% block pagecontent %}
  {% include 'includes/form.html' %}
{% endblock pagecontent %}

templates/userDashboard/user/add_skill.html
{% extends 'userDashboard/index.html'%}

{% block title %}
  <title>StartupNep | Add Skills</title>
{% endblock title %}

{% block pagecontent %}
  {% include 'includes/form.html' %}
{% endblock pagecontent %}

templates/userDashboard/user/education.html
{% extends 'userDashboard/index.html' %}

{% block title %}
  <title>StartupNep | Education</title>
{% endblock title %}

{% block pagecontent %}
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>List of Your Education Background</h5>
        <span class="right"><a href="{% url 'enduser:add-education' %}" class="btn btn-primary btn-round">Add</a></span>
      </div>
      <div class="card card-pad-sm table-responsive">
        {% if education %}
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Course</th>
              <th>Start Date</th>
              <th>End Date</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for edu in education %}
              <tr>
                <td>{{ edu.id }}</td>
                <td>{{ edu.name }}</td>
                <td>{{ edu.course }}</td>
                <td>{{ edu.start_date }}</td>
                <td>{{ edu.end_date }}</td>
                <td><a href="{{ edu.edit_education_url }}">Edit</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
          {% else %}
            <p>There is no data</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock pagecontent %}

templates/userDashboard/user/experience.html
{% extends 'userDashboard/index.html' %}

{% block title %}
  <title>StartupNep | Education</title>
{% endblock title %}

{% block pagecontent %}
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>List of Your Experiences</h5>
        <span class="right"><a href="{% url 'enduser:add-experience' %}" class="btn btn-primary btn-round">Add</a></span>
      </div>
      <div class="card card-pad-sm table-responsive">
        {% if experiences %}
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Designation</th>
              <th>Company</th>
              <th>Start Date</th>
              <th>End Date</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for experience in experiences %}
              <tr>
                <td>{{ experience.id }}</td>
                <td>{{ experience.designation }}</td>
                <td>{{ experience.company }}</td>
                <td>{{ experience.start_date }}</td>
                <td>{{ experience.end_date }}</td>
                <td><a href="{{ experience.edit_experience_url }}">Edit</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
          {% else %}
            <p>There is no data</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock pagecontent %}

templates/userDashboard/user/reference.html
{% extends 'userDashboard/index.html' %}

{% block title %}
  <title>StartupNep | Education</title>
{% endblock title %}

{% block pagecontent %}
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>List of Your References</h5>
        <span class="right"><a href="{% url 'enduser:add-reference' %}" class="btn btn-primary btn-round">Add</a></span>
      </div>
      <div class="card card-pad-sm table-responsive">
        {% if references %}
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Name of Referee</th>
              <th>Designation of Referee</th>
              <th>Phone Number</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for reference in references %}
              <tr>
                <td>{{ reference.id }}</td>
                <td>{{ reference.name_of_refree }}</td>
                <td>{{ reference.designation_of_refree }}</td>
                <td>{{ reference.phone_number }}</td>
                <td><a href="{{ reference.edit_reference_url }}">Edit</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
          {% else %}
            <p>There is no data</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock pagecontent %}

templates/userDashboard/user/resume.html
{% extends 'userDashboard/index.html' %}

{% block title %}
  <title>StartupNep | Resume</title>
{% endblock title %}

{% block pagecontent %}
  {% include 'includes/form.html' %}
{% endblock pagecontent %}

templates/userDashboard/user/skill.html
{% extends 'userDashboard/index.html' %}

{% block title %}
  <title>StartupNep | Education</title>
{% endblock title %}

{% block pagecontent %}
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>List of Your Skills</h5>
        <span class="right"><a href="{% url 'enduser:add-skill' %}" class="btn btn-primary btn-round">Add</a></span>
      </div>
      <div class="card card-pad-sm table-responsive">
        {% if skills %}
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for skill in skills %}
              <tr>
                <td>{{ skill.id }}</td>
                <td>{{ skill.name }}</td>
                <td><a href="{{ skill.edit_skill_url }}">Edit</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
          {% else %}
            <p>There is no data</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock pagecontent %}

templates/userDashboard/user/user_setting.html
{% extends 'userDashboard/index.html' %}

{% block title %}
  <title>StartupNep | UserSetting</title>
{% endblock title %}

{% block pagecontent %}
  {% include 'includes/form.html' %}
{% endblock pagecontent %}