job/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^jobs$', views.list_job, name="list-job"),
    url(r'^job/(?P<slug>[-\w]+)$', views.detail_job, name="job-detail"),
    url(r'^post/job$', views.post_job, name="post-job"),
    url(r'^edit/job/(?P<slug>[-\w]+)$', views.edit_job, name="edit-job"),
    url(r'^apply/job/(?P<slug>[-\w]+)$', views.apply_job, name="apply-job"),
]

products/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^dashboard$', views.dashboard, name="dashboard"),
    url(r'^list/company$', views.list_company, name="list-company"),
    url(r'^list/company/(?P<slug>[-\w]+)$',
        views.view_company, name="view-company"),
    url(r'^list/my-company$',
        views.list_my_company, name="list-my-company"),
    url(r'^list/product/(?P<slug>[-\w]+)$',
        views.view_product, name="view-product"),
    url(r'^list/my-products$',
        views.list_my_product, name="list-my-product"),
    url(r'^post/company$', views.post_company, name="post-company"),
    url(r'^edit/company/(?P<slug>[-\w]+)$',
        views.edit_company, name="edit-company"),
    url(r'^post/product$', views.post_product, name="post-product"),
    url(r'^edit/product/(?P<slug>[-\w]+)$',
        views.edit_product, name="edit-product"),
    url(r'^post/achievement$', views.post_achievement, name="post-achievement"),
    url(r'^edit/achievement/(?P<slug>[-\w]+)$',
        views.edit_achievement, name="edit-achievement"),
    url(r'^list/my-achievements$',
        views.list_my_achievement, name="list-my-achievements"),
    url(r'^post/founder$', views.post_founder, name="post-founder"),
    url(r'^edit/founder/(?P<slug>[-\w]+)$',
        views.edit_founder, name="edit-founder"),
    # url(r'^like/company/(?P<slug>[-\w]+)$',
    #     views.CompanyLikesAPIView.as_view(), name="like-company"),
    url(r'^like/company$',
        views.CompanyLikesAPIView.as_view(), name="like-company"),
    url(r'^blog$', views.blog, name="blog"),
    url(r'^accounts/profile/$', views.update_profile, name="profile"),
]

startup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('products.urls', namespace='products')),
    url(r'^', include('job.urls', namespace='jobs')),
    url(r'^', include('enduser.urls', namespace='enduser')),
    #url(r'^', include('resume.urls', namespace='resume')),
    url(r'^', include('investors.urls', namespace='investors')),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

templates/company/home.html
{% extends 'base.html' %}
{% load static %}
{% block pagecontent %}
	<div class="main main-raised">
		<div class="container">
			<div class="section text-center section-landing">
				<div class="row">
						<h2 class="title">TOP CATEGORIES</h2>
					<div class="col-md-6">
						<div class="startup-banner1" style="background-image: url('{% static 'img/startup1.svg'%}');">
					</div> 
					</div>
					<div class="col-md-6">
						<div class="features">
							{% for category in categories %}
										<ul class="category-list-group collection">
											<li class="collection-item category-list">
												<span class="list-title">
													<a href="/list/company?category={{category.slug}}">{{ category }} ({{ category.product_count}})</a>
													<i class="material-icons">arrow_forward</i>
												</span>
											
											</li>
										</ul>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
		<section class="content-section text-center">
			<h1>Do you want to post the job?</h1>
			<div class="content-bg job-filter">
			</div>
			<a class="btn btn-primary btn-round" href="{% url 'jobs:post-job' %}">Post Job</a>
		</section>
		{% if companies %}
		<div class="container">
		<div class="section text-center">
			<h2 class="title">COMPANIES</h2>
			{% for company in companies %}
				{% if forloop.first %}<div class="row top-company-grid">{% endif %}
				<div class="col-md-4">
					<div class="card card-01">
						<div class="profile-box">
							<img class="card-img-top img-circle img-responsive" src="{{ company.logo.url }}" alt="Card image cap">
						</div>
						<div class="card-body text-center">
							<h4><a href="{{ company.get_absolute_url }}">{{ company.name}}</a></h4>
							<p class="card-text">{{ company.description|truncatechars:90 }}</p>
							<span class="social-box">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-google-plus"></i></a>
							</span>
						</div>
						<br />
					</div>
				</div>
				{% if forloop.counter|divisibleby:4 %}</div><br/><div class="row">{% endif %}
				{% if forloop.last %}</div>{% endif %}
			{% endfor %}
		{% endif %}
		</div>
		</div>
		<section class="content-section">
		<h1>content k raknu sochdai xu</h1>
			<div class="content-right-bg">
			</div>
		</section>
		<br />
		<br />
		<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="startup-banner1" style="background-image: url('{% static 'img/startup4.jpg'%}');">
			</div>
			</div>
			<div class="col-md-6">
				<h2 class="title" style="text-align: center;">Why Startup?</h2>
				<p>Startup Nepal to bring all the startups, investors and users community in a single place.
					Startup Nepal to bring all the startups, investors and users community in a single place
					Startup Nepal to bring all the startups, investors and users community in a single place
					Startup Nepal to bring all the startups, investors and users community in a single place
					Startup Nepal to bring all the startups, investors and users community in a single place
					Startup Nepal to bring all the startups, investors and users community in a single place
					Startup Nepal to bring all the startups, investors and users community in a single place
					Startup Nepal to bring all the startups, investors and users community in a single place
				</p>
			</div>
			</div>
		</div>
			
		</div>
</div>
{% endblock pagecontent %}

templates/company/job_detail.html
{% extends 'base.html' %}
{% block banner %}
	<div class="empty-block"><br/></div>
{% endblock banner %}
{% block pagecontent %}
	<div class="container">
				<div class="card card-01">
					<div class="card-body text-center">
						<h3 class="card-title text-center">{{ job.name }}</h3>
						<p class="card-text">{{ job.description|safe }}</p>
						{% if request.user.is_staff %}
							<a href="{{ job.get_edit_url }}" class="btn btn-primary btn-round">Edit</a>
							{% else %}
							<a href="{{ job.get_job_apply_url }}" class="btn btn-primary btn-round">Apply</a>
						{% endif %}
					</div>
				</div>
	</div>
{% endblock pagecontent %}

templates/company/list_company.html
{% extends 'base.html' %}
{% block banner %}
	<div class="empty-block"><br/></div>
{% endblock banner %}
{% block pagecontent %}
	<div class="container">
		<div class="filter-block">
			<span class="filter-icon">
				<i class="fa fa-filter fa-3x"></i> <span class="btn btn-primary">Filter</span>
			</span>
		</div>
		{% for company in companies %}
			{% with total_likes=company.likes.count users_like=company.likes.all %}
			{% if forloop.first %}<div class="row">{% endif %}
			<div class="col-md-4">
				<div class="card card-01">
					<div class="profile-box">
						<img class="card-img-top rounded-circle" src="{{ company.logo.url }}" alt="Card image cap">
					</div>
					<div class="card-body text-center">
						<span class="badge-box"><i class="fa fa-check"></i></span>
						<h3 class="card-title text-center">{{ company.name }}</h3>
						<p class="card-text">{{ company.description|truncatechars:90 }}</p>
						<a href="{{ company.get_absolute_url }}" class="btn btn-link">View Detail</a>
						<span class="count">
							<span class="total">{{ total_likes }}</span>
							like{{ total_likes|pluralize }}
						</span>
					<div class="social-box">
						<a href="{{company.facebook}}"><i class="fa fa-facebook"></i></a>
						<a href="{{company.twitter}}"><i class="fa fa-twitter"></i></a>
						<a href="{{company.linkedin}}"><i class="fa fa-google-plus"></i></a>
					</div><br />
				</div>
			</div>
		</div>
		{% if forloop.counter|divisibleby:4 %}</div><br/><div class="row">{%endif %}
		{% if forloop.last %}</div>{% endif %}
	{% endwith %}
{% endfor %}
</div>
{% endblock pagecontent %}

templates/company/list_job.html
{% extends 'base.html' %}
{% block banner %}
	<div class="empty-block"><br/></div>
{% endblock banner %}
{% block pagecontent %}
	<div class="container">
		<div class="filter-block">
			<span class="filter-icon">
				<i class="fa fa-filter fa-3x"></i> <span class="btn btn-primary">Filter</span>
			</span>
		</div>
		{% for job in jobs %}
			{% if forloop.first %}<div class="row">{% endif %}
			<div class="col-md-4">
				<div class="card card-01">
					<div class="card-body text-center">
						<h4 class="card-title text-center">{{ job.company.name }}</h4>
						<p class="card-text">{{ job.name }}</p>
						<a href="{{ job.get_absolute_url }}" class="btn btn-link">View Detail</a>
					</div>
				</div>
			</div>
			{% if forloop.counter|divisibleby:4 %}</div><br/><div class="row">{%endif %}
			{% if forloop.last %}</div>{% endif %}
		{% endfor %}
	</div>
{% endblock pagecontent %}

templates/company/post_company.html
{% extends 'base.html' %}
{% load add_css %}
{% block pagecontent %}
	<div class="main main-raised">
		<div class="container">
			<div class="section">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<form class="form" role="form" action="" method="post" enctype='multipart/form-data'>
							{% csrf_token %}
							{% for field in form %}
								{% if field.errors %}
									<div class="form-group label-floating has-error">
										<label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
										<div class="col-sm-10">
											{{ field.type }}
											{{ field|add_css:'form-control' }}
											<span class="help-block">
											{% for error in  field.errors %}{{ error }}{% endfor %}
										</span>
									</div>
								</div>
							{% else %}
								<div class="form-group label-floating">
									<label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
									{{ field|add_css:'form-control' }}
									{% if field.help_text %}
										<p class="help-block"><small>{{ field.help_text }}</small></p>
									{% endif %}
								</div>
							{% endif %}
						{% endfor %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-primary btn-round">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock pagecontent %}

{% block js %}
	{{ block.super }}
	<script>
		$(".datepicker").datepicker( {
		    format: " yyyy",
		    viewMode: "years", 
		    minViewMode: "years"
		});
	</script>
{% endblock js %}

templates/company/post_job.html
{% extends 'base.html' %}
{% load static add_css %}
{% block banner %}
{% endblock banner %}
{% block pagecontent %}
	<div class="">
		<section class="content-section text-center">
			<div class="content-bg job-filter">
			</div>
		</section>
		<div class="container">
			<div class="section" style="padding: 5px">
				<h2 class="text-center title">POST JOB </h2>
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<div class="job-form-card">
							<div class="left"></div>
							<div class="right">
								{% include 'includes/form.html' %}
							</div>
							{{ form.media }}
						</div>
					</div>
				</div>
			</div>
		</div>
		<section class="content-section text-center">
			<div class="content-right-bg job-filter">
			</div>
		</section>
	{% endblock pagecontent %}

templates/company/post_product.html
{% extends 'base.html' %}
{% load add_css %}
{% block pagecontent %}
    <form class="form-horizontal" role="form" action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            {% if field.errors %}
                <div class="form-group has-error">
                    <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field|add_css:'form-control' }}
                        <span class="help-block">
                        {% for error in  field.errors %}{{ error }}{% endfor %}
                    </span>
                </div>
            </div>
        {% else %}
            <div class="form-group">
                <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                <div class="col-sm-10">
                    {{ field|add_css:'form-control' }}
                    {% if field.help_text %}
                        <p class="help-block"><small>{{ field.help_text }}</small></p>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
    {# {{form.as_p}} #}
</form>
{% endblock pagecontent %}

templates/company/view_company.html
{% extends 'base.html' %}
{% block banner %}
  <div class="header header-filter" style="background-image: url('{{ company.banner.url }}');"></div>
{% endblock banner %}
{% block pagecontent %}
{% with total_likes=company.likes.count users_like=company.likes.all %}
  <div class="main main-raised">
    <div class="profile-content">
      <div class="container">
        <div class="row">
          <div class="profile">
            <div class="avatar">
              <img src="{{ company.logo.url }}" alt="Circle Image" class="img-circle img-responsive img-raised" style="width: 160px !important; height: 160px; margin: 0 auto;">
            </div>
            <div class="name" style="text-align: center;">
              <h3 class="title">{{company.name}}</h3>
              <span class="count">
              <span class="total">{{ total_likes }}</span>
              like{{ total_likes|pluralize }}
            </span>
              <a href="#" data-id="{{ company.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="company-like like-{{ company.id}} btn btn-link"><i class="fa fa-thumbs-o-up"></i>
            {% if request.user not in users_like %}
              Like
            {% else %}
              Unlike
            {% endif %}
          </a>
            </div>
            <div class="category-tag text-center">
              <span class="tag">Startup</span>
              <span class="tag">Incubator</span>
              <span class="tag">IOT</span>
            </div>
          </div>
        </div><br />
        <div class="description text-center">
          <p>{{company.description}}</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="profile-tabs">
          <div class="nav-align-center">
            <ul class="nav nav-pills" role="tablist">
              <li>
                <a href="#social-connection" role="tab" data-toggle="tab">
                  <i class="material-icons">camera</i>
                  Social Connection
                </a>
              </li>
              <li class="active">
                <a href="#products" role="tab" data-toggle="tab">
                  <i class="material-icons">palette</i>
                  Products
                </a>
              </li>
              <li>
                <a href="#founders" role="tab" data-toggle="tab">
                  <i class="material-icons">favorite</i>
                  Founders
                </a>
              </li>
              <li>
                <a href="#achievements" role="tab" data-toggle="tab">
                  <i class="material-icons">favorite</i>
                  Achievements
                </a>
              </li>
            </ul>
            <div class="tab-content gallery">
              <div class="tab-pane" id="social-connection">
                <div class="row">
                  <div class="social-box">
                    <a href="{{company.facebook}}"><i class="fa fa-facebook"></i></a>
                    <a href="{{company.twitter}}"><i class="fa fa-twitter"></i></a>
                    <a href="{{company.linkedin}}"><i class="fa fa-google-plus"></i></a>
                  </div>
                </div>
              </div>
              <div class="tab-pane text-center active" id="products">
                <div class="row">
                  {% if products %}
                    <h3>Products</h3>
                    <div class="products">
                      {% for product in products %}
                        {% if forloop.first %}<div class="row">{% endif %}
                        <div class="col-md-6">
                          <div class="card card-01">
                            <div class="profile-box">
                              
                            </div>
                            <div class="card-body text-center">
                              <span class="badge-box"><i class="fa fa-check"></i></span>
                              <h3 class="card-title text-center">{{ product.name }}</h3>
                              <p class="card-text">{{ product.description|truncatechars:90 }}</p>
                              <a class="btn btn-primary" href={% url 'products:edit-product' slug=product.slug %}>Edit</a>
                            </div>
                          </div>
                        </div>
                        {% if forloop.counter|divisibleby:4 %}</div><br/><div class="row">{%endif %}
                        {% if forloop.last %}</div>{% endif %}
                      {% endfor %}
                    </div>
                  {% endif %}
                </div>
              </div>
              <div class="tab-pane text-center" id="founders">
                <div class="row">
                  Founders left
                </div>
              </div>
              <div class="tab-pane text-center" id="achievements">
                <div class="row">
                  Achievements
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- End Profile Tabs -->
      </div>
    </div>
  </div>
  <footer class="footer">
    <div class="container">
      <nav class="pull-left">
        <ul>
          <li>
            <a href="{% url 'products:home' %}">
              Startup
            </a>
          </li>
          <li>
            <a href="">
              About Us
            </a>
          </li>
          <li>
            <a href="">
              Blog
            </a>
          </li>
        </ul>
      </nav>
      <div class="copyright pull-right">
        &copy; 2017, made with <i class="fa fa-heart heart"></i> by Connyct
      </div>
    </div>
  </footer>
  {% endwith %}
{% endblock pagecontent %}

templates/company/view_product.html
{% extends 'base.html' %}
{% block pagecontent %}
	<div class="container">
		<div class="content">
			Name: {{ product.name }}
			Description: {{ product.description }}<br/>
			categories: <p>{% for category in categories %} {{ category.name }}{{ category.product_count }}<br/> {% endfor %}</p>
		</div>
		{% if request.user.is_authenticated %}
		<div class="action">
			<a class="btn btn-primary" href={% url 'products:edit-product' slug=product.slug %}>Edit</a>
		</div>
		{% endif %}
	</div>
{% endblock pagecontent %}