job/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^jobs$', views.list_job, name="list-job"),
    url(r'^job/(?P<slug>[-\w]+)$', views.detail_job, name="job-detail"),
    url(r'^post/job$', views.post_job, name="post-job"),
    url(r'^edit/job/(?P<slug>[-\w]+)$', views.edit_job, name="edit-job"),
    url(r'^apply/job/(?P<slug>[-\w]+)$', views.apply_job, name="apply-job"),
]

products/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^dashboard$', views.dashboard, name="dashboard"),
    url(r'^list/company$', views.list_company, name="list-company"),
    url(r'^list/company/(?P<slug>[-\w]+)$',
        views.view_company, name="view-company"),
    url(r'^list/my-company$',
        views.list_my_company, name="list-my-company"),
    url(r'^list/product/(?P<slug>[-\w]+)$',
        views.view_product, name="view-product"),
    url(r'^list/my-products$',
        views.list_my_product, name="list-my-product"),
    url(r'^post/company$', views.post_company, name="post-company"),
    url(r'^edit/company/(?P<slug>[-\w]+)$',
        views.edit_company, name="edit-company"),
    url(r'^post/product$', views.post_product, name="post-product"),
    url(r'^edit/product/(?P<slug>[-\w]+)$',
        views.edit_product, name="edit-product"),
    url(r'^post/achievement$', views.post_achievement, name="post-achievement"),
    url(r'^edit/achievement/(?P<slug>[-\w]+)$',
        views.edit_achievement, name="edit-achievement"),
    url(r'^list/my-achievements$',
        views.list_my_achievement, name="list-my-achievements"),
    url(r'^post/founder$', views.post_founder, name="post-founder"),
    url(r'^edit/founder/(?P<slug>[-\w]+)$',
        views.edit_founder, name="edit-founder"),
    # url(r'^like/company/(?P<slug>[-\w]+)$',
    #     views.CompanyLikesAPIView.as_view(), name="like-company"),
    url(r'^like/company$',
        views.CompanyLikesAPIView.as_view(), name="like-company"),
    url(r'^blog$', views.blog, name="blog"),
    url(r'^accounts/profile/$', views.update_profile, name="profile"),
]

startup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('products.urls', namespace='products')),
    url(r'^', include('job.urls', namespace='jobs')),
    url(r'^', include('enduser.urls', namespace='enduser')),
    #url(r'^', include('resume.urls', namespace='resume')),
    url(r'^', include('investors.urls', namespace='investors')),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block title %}
    <title>StartupNep</title>
    {% endblock title %}
    {% block css %}
      {% include 'includes/css.html' %}
    {% endblock css %}
    
  </head>
  <body class="homepage index-page">
      {% include 'includes/navbar.html'%}

      <div class="wrapper">
        {% block banner %}
          <div class="header header-filter" style="background-image: url('{% static 'img/bg2.jpeg'%}');">
            <div class="container">
              <div class="row">
                <div class="col-md-8 col-md-offset-2">
                  <div class="brand">
                    <h1>Startup Nepal</h1>
                    <h3>Startup Nepal to bring all the startups, investors and users community in a single place</h3>
                  </div>
                </div>
              </div>

            </div>
          </div>
        {% endblock banner %}
        {% block pagecontent %}
        {% endblock pagecontent %}
        {% block footer %}
          {% include 'includes/footer.html' %}
        {% endblock footer %}
      </div>

      {% block js %}
        {% include 'includes/js.html' %}
         
    {% endblock js %}
    </body>
  </html>

templates/form.html
{% load add_css %}
	<div class="row">
		<div class="col-lg-12">
			<div class="text-center m-t-lg">
				<form class="form-horizontal" role="form" action="" method="post" enctype='multipart/form-data'>
					{% csrf_token %}
					{% for field in form %}
						{% if field.errors %}
							<div class="form-group has-error">
								<label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
								<div class="col-sm-10">
									{{ field|add_css:'form-control' }}
									<span class="help-block">
									{% for error in  field.errors %}{{ error }}{% endfor %}
								</span>
							</div>
						</div>
					{% else %}
						<div class="form-group">
							<label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
							<div class="col-sm-10">
								{{ field|add_css:'form-control' }}
								{% if field.help_text %}
									<p class="help-block"><small>{{ field.help_text }}</small></p>
								{% endif %}
							</div>
						</div>
					{% endif %}
				{% endfor %}
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn btn-primary">Submit</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>StartupNEP</title>
        <link href="{% static 'dashboard/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'dashboard/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
        <link href="{% static 'dashboard/css/animate.css' %}" rel="stylesheet">
        <link href="{% static 'dashboard/css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar-default navbar-static-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav metismenu" id="side-menu">
                        <li class="nav-header">
                            <div class="dropdown profile-element">
                                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                    <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">{{request.user.username}}</strong>
                                    </span> </span> </a>
                                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                        <li><a href="{% url 'account_logout' %}">Logout</a></li>
                                    </ul>
                                </div>
                            </li>
                            <li class="active">
                                <a href=""><i class="fa fa-building-o"></i> <span class="nav-label">Company</span> <span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li class="{% if request.path == "/post/company"%}active{% endif %}"><a href="{% url 'products:post-company' %}">Add Company</a></li>
                                    <li class="{% if request.path == "/list/my-company"%}active{% endif %}"><a href="{% url 'products:list-my-company' %}">Company List</a></li>
                                </ul>
                            </li>
                            <li class="{% if request.path == "/post/product" or request.path == "/list/my-products" %}active{% endif %}">
                                <a href=""><i class="fa fa-laptop"></i> <span class="nav-label">Product</span> <span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li class="{% if request.path == "/post/product"%}active{% endif %}"><a href="{% url 'products:post-product' %}">Add Product</a></li>
                                    <li class="{% if request.path == "/list/my-products"%}active{% endif %}"><a href="{% url 'products:list-my-product' %}">Product List</a></li>
                                </ul>
                            </li>
                               <li class="{% if request.path == "/post/achievement" or request.path == "/list/my-achievements" %}active{% endif %}">
                                <a href=""><i class="fa fa-trophy"></i> <span class="nav-label">Achievement</span> <span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li class="{% if request.path == "/post/achievement"%}active{% endif %}"><a href="{% url 'products:post-achievement' %}">Add Achievement</a></li>
                                    <li class="{% if request.path == "/list/my-achievements"%}active{% endif %}"><a href="{% url 'products:list-my-achievements' %}">Achievement List</a></li>
                                </ul>
                            </li>
                    <li class="{% if request.path == "/post/founder"%}active{% endif %}">
                    <a href="{% url 'products:post-founder' %}"><i class="fa fa-users"></i> <span class="nav-label">Founders</span> </a>
                </li>
                <li class="{% if request.path == "/blog"%}active{% endif %}">
                <a href="{% url 'products:blog' %}"><i class="fa fa-rss-square"></i> <span class="nav-label">Blog</span> </a>
            </li>
            <li class="{% if request.path == "/accounts/profile/"%}active{% endif %}">
            <a href="{% url 'products:profile' %}"><i class="fa fa-user"></i> <span class="nav-label">Profile</span> </a>
        </li>
    </ul>
</div>
</nav>
<div id="page-wrapper" class="gray-bg">
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="#">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="{% url 'account_logout' %}">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    {% block pagecontent %}
    {% endblock pagecontent %}
</div>
<div class="footer">
    <div>
        <strong>Copyright</strong> StartupNEP &copy; 2017
    </div>
</div>
</div>
</div>
<!-- Mainly scripts -->
<script src="{% static 'dashboard/js/jquery-3.1.1.min.js'%}"></script>
<script src="{% static 'dashboard/js/bootstrap.min.js'%}"></script>
<script src="{% static 'dashboard/js/plugins/metisMenu/jquery.metisMenu.js'%}"></script>
<script src="{% static 'dashboard/js/plugins/slimscroll/jquery.slimscroll.min.js'%}"></script>
<!-- Custom and plugin javascript -->
<script src="{% static 'dashboard/js/inspinia.js'%}"></script>
<script src="{% static 'dashboard/js/plugins/pace/pace.min.js'%}"></script>
</body>
</html>