enduser/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^user$', views.user_dashboard, name="user-dashboard"),
    url(r'^add/resume$', views.resume_form, name="add-resume"),
    url(r'^edit/resume/(?P<slug>[-\w]+)$', views.edit_resume_form, name="edit-resume"),
    url(r'^education$', views.education, name="education"),
    url(r'^add/education$', views.add_education, name="add-education"),
    url(r'^edit/education/(?P<id>[0-9]+)$', views.edit_education, name="edit-education"),
    url(r'^experience$', views.experience, name="experience"),
    url(r'^add/experience$', views.add_experience, name="add-experience"),
    url(r'^edit/experience/(?P<id>[0-9]+)$', views.edit_experience, name="edit-experience"),
    url(r'^skill$', views.skill, name="skill"),
    url(r'^add/skill$', views.add_skill, name="add-skill"),
    url(r'^edit/skill/(?P<id>[0-9]+)$', views.edit_skill, name="edit-skill"),
    url(r'^reference$', views.reference, name="reference"),
    url(r'^add/reference$', views.add_reference, name="add-reference"),
    url(r'^edit/reference/(?P<id>[0-9]+)$', views.edit_reference, name="edit-reference"),
    url(r'^add/setting$', views.usersetting, name="usersetting"),
    url(r'^edit/setting/(?P<id>[0-9]+)$', views.edit_usersetting, name="edit-usersetting"),
]

job/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^jobs$', views.list_job, name="list-job"),
    url(r'^job/(?P<slug>[-\w]+)$', views.detail_job, name="job-detail"),
    url(r'^post/job$', views.post_job, name="post-job"),
    url(r'^edit/job/(?P<slug>[-\w]+)$', views.edit_job, name="edit-job"),
    url(r'^apply/job/(?P<slug>[-\w]+)$', views.apply_job, name="apply-job"),
]

products/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^dashboard$', views.dashboard, name="dashboard"),
    url(r'^list/company$', views.list_company, name="list-company"),
    url(r'^list/company/(?P<slug>[-\w]+)$',
        views.view_company, name="view-company"),
    url(r'^list/my-company$',
        views.list_my_company, name="list-my-company"),
    url(r'^list/product/(?P<slug>[-\w]+)$',
        views.view_product, name="view-product"),
    url(r'^list/my-products$',
        views.list_my_product, name="list-my-product"),
    url(r'^post/company$', views.post_company, name="post-company"),
    url(r'^edit/company/(?P<slug>[-\w]+)$',
        views.edit_company, name="edit-company"),
    url(r'^post/product$', views.post_product, name="post-product"),
    url(r'^edit/product/(?P<slug>[-\w]+)$',
        views.edit_product, name="edit-product"),
    url(r'^post/achievement$', views.post_achievement, name="post-achievement"),
    url(r'^edit/achievement/(?P<slug>[-\w]+)$',
        views.edit_achievement, name="edit-achievement"),
    url(r'^list/my-achievements$',
        views.list_my_achievement, name="list-my-achievements"),
    url(r'^post/founder$', views.post_founder, name="post-founder"),
    url(r'^edit/founder/(?P<slug>[-\w]+)$',
        views.edit_founder, name="edit-founder"),
    # url(r'^like/company/(?P<slug>[-\w]+)$',
    #     views.CompanyLikesAPIView.as_view(), name="like-company"),
    url(r'^like/company$',
        views.CompanyLikesAPIView.as_view(), name="like-company"),
    url(r'^blog$', views.blog, name="blog"),
    url(r'^accounts/profile/$', views.update_profile, name="profile"),
]

startup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('products.urls', namespace='products')),
    url(r'^', include('job.urls', namespace='jobs')),
    url(r'^', include('enduser.urls', namespace='enduser')),
    #url(r'^', include('resume.urls', namespace='resume')),
    url(r'^', include('investors.urls', namespace='investors')),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

templates/includes/dashboard/user/nav.html
<nav class="navbar navbar-default navbar-fixed">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        {{request.user.username}}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="">Edit Profile</a></li>
                        <li><a href="{% url 'account_logout' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/includes/dashboard/user/sidebar.html
<nav class="navbar-default navbar-static-side" role="navigation">
<div class="sidebar-collapse">
  <ul class="nav metismenu" id="side-menu">
    <li class="nav-header">
      <div class="dropdown profile-element">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">{{request.user.username}}</strong>
            </span> </span> </a>
        <ul class="dropdown-menu animated fadeInRight m-t-xs">
          <li><a href="{% url 'account_logout' %}">Logout</a></li>
        </ul>
      </div>
    </li>
    <li class="active">
      <a href=""><i class="fa fa-building-o"></i> <span class="nav-label">Resume</span> <span class="fa arrow"></span></a>
      <ul class="nav nav-second-level">
        <li class="{% if request.path == "/add/resume"%}active{% endif %}"><a href="{% url 'enduser:add-resume' %}">Personal Detail</a></li>
        <li class="{% if request.path == "/education"%}active{% endif %}"><a href="{% url 'enduser:education' %}">Education</a></li>
        <li class="{% if request.path == "/experience"%}active{% endif %}"><a href="{% url 'enduser:experience' %}">Experience</a></li>
        <li class="{% if request.path == "/skill"%}active{% endif %}"><a href="{% url 'enduser:skill' %}">Skill</a></li>
        <li class="{% if request.path == "/reference"%}active{% endif %}"><a href="{% url 'enduser:reference' %}">Reference</a></li>
      </ul>
    </li>
    <li class="{% if request.path == "/add/setting"%}active{% endif %}">
      <a href="{% url 'enduser:usersetting' %}"><i class="fa fa-user"></i> <span class="nav-label">Settings</span> </a>
    </li>
    <li class="{% if request.path == " /accounts/profile/ "%}active{% endif %}">
      <a href="{% url 'products:profile' %}"><i class="fa fa-user"></i> <span class="nav-label">Profile</span> </a>
    </li>
    <li class="{% if request.path == " /accounts/profile/ "%}active{% endif %}">
      <a href="{% url 'products:profile' %}"><i class="fa fa-user"></i> <span class="nav-label">Feedback</span> </a>
    </li>
  </ul>
</div>
</nav>